version: "3.8"
services:
  drone:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITLAB_SERVER=http://192.168.8.191:10080
      - DRONE_GITLAB_CLIENT_ID=e2d25183082c136c9d41f740500119fbcdb0604baf054117ab0f20be1688f0c2
      - DRONE_GITLAB_CLIENT_SECRET=fb3317fbec994e3fd104f85c22c9a3f83948b4e758535810eb668313e034a9a5
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
      - DRONE_SERVER_HOST=drone.cza.orz
      - DRONE_SERVER_PROTO=http
  driver:
    image: drone/drone-runner-docker:1
    container_name: drone-driver
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_HOST=192.168.8.191
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner
