global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'go-test'
    scrape_interval: 5s  # Override the global default and scrape targets from this job every 5 seconds.
    static_configs:
      - targets: ['192.168.8.191:8080']
        labels:
          input: 'true'
          minorType: 'gen'
